### ISSUE TITLE
Minor Fix - Fix `Apply Now` Button (looks weird)

### ISSUE THREAD

**Issue by mlin2020** [FindoraNetwork/findora-wiki#160]
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/77126297/171757895-c58b262a-b23f-4932-8066-e692fd0b6144.png">

**Comment by dlin128** [comment]
<img width="475" alt="image" src="https://user-images.githubusercontent.com/3413642/172717568-9c4ceeb6-e049-4c48-94d9-b59e71d35931.png">

Dev Wiki ^

Seems this has been addressed and should go live when merged to main.
