### ISSUE TITLE
[TestNet]: actual docker image must not be tagged as latest

### ISSUE THREAD

**Issue by paparai** [FindoraNetwork/findora-wiki#82]
Since there is no difference  for Findora's testnet/mainnet  docker images names/tags  at docker registry https://hub.docker.com/r/findoranetwork/findorad/tags current [testnet install script](https://github.com/FindoraNetwork/findora-wiki/blob/main/docs/guides/node_init_testnet.sh) contains a critical error.

In particular current testnet's docker image is tagged as v0.3.0-release(output for testnode with docker image set up 3 week ago):
```
$ curl http://localhost:8669/version
Build: v0.3.0-release 2021-12-06  

```

output for testnode with docker image set up 3 week ago(tag latest set correctly on 2021-12-06) 

```
$ docker images 
REPOSITORY                TAG                  IMAGE ID       CREATED         SIZE
findoranetwork/findorad   latest               a3e4b4019cbf   3 weeks ago    165MB
```

But since 3 weeks node_init_testnet.sh will pull **findoranetwork/findorad:latest** wich means it will download v0.3.11-release(has tag latest and applicable for mainnet only) and testnode fail to catchup.

**Comment by jianwel** [comment]
@jimmy-findora should we close this issue?

**Comment by paparai** [comment]
> @jimmy-findora should we close this issue?
Yes, since we have different tags for mainnet and testnet feel free to close

**Comment by jimmysun0815** [comment]
Hi @paparai  Yes I think the init and update script can catch the live version from Testnet and Mainnet now. I think everything should be fine. Thanks for report. 
Hope everything good in your side dude.
